#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pyeclib
Version  : 1.0.7
Release  : 2
URL      : https://bitbucket.org/kmgreen2/pyeclib/get/v1.0.7.tar.bz2
Source0  : https://bitbucket.org/kmgreen2/pyeclib/get/v1.0.7.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-2-Clause
Requires: pyeclib-python
BuildRequires : less
BuildRequires : liberasurecode-dev
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : setuptools
BuildRequires : vim
Patch1: 0001-Fix-build-for-x64.patch

%description
This is v1.0 of PyECLib.  This library provides a simple Python interface for
implementing erasure codes and is known to work with Python v2.6, 2.7 and 3.x.

%package python
Summary: python components for the pyeclib package.
Group: Default

%description python
python components for the pyeclib package.


%prep
%setup -q -n kmgreen2-pyeclib-aa58aa887c23
%patch1 -p1

%build
python2 setup.py build -b py2

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
python2 setup.py test
%install
rm -rf %{buildroot}
python2 setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
